version: '3.8'

services:
#  calculation-api:
#    container_name: calculation-api
#    image: lluongo/calculation-api:latest
#    ports:
#      - "8090:8090"
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - app-network
#
#  return-percentage:
#    container_name: return-percentage-api
#    image: lluongo/return-percentage-api:latest
#    ports:
#      - "8091:8091"
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: