
# api and spring configs
server:
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: calculation-api
  devtools:
    restart:
      enabled: true
  cache:
    type: redisson
  redis:
    config:
      import: classpath:/redisson.yml
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

# general configs
get_percentage_url: "http://host.docker.internal:8091/v1/percentage"
error_429_Message: "Too many requests - please try again later."

# 429 to many values parameters
number_of_request: 3
duration: 1

# redis configs
rate_limiter_key: "apiRateLimiterKey"
redisson_config_yml:  "redisson.yml"
percentage_cache_key: "percentageCacheKey"